package org.nb.mybatis.model;

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class NB_Entity {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_entity.nb_id
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	private Integer nbId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_entity.nb_content
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	private String nbContent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_entity.nb_image
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	private String nbImage;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_entity.nb_auther
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	private Integer nbAuther;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_entity.nb_examiner
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	private Integer nbExaminer;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_entity.nb_pubtime
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	private Date nbPubtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_entity.nb_status
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	private Integer nbStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_entity.nb_up
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	private Integer nbUp;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_entity.nb_down
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	private Integer nbDown;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_entity.nb_label
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	private String nbLabel;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_entity.nb_id
	 * 
	 * @return the value of nb_entity.nb_id
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public Integer getNbId() {
		return nbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_entity.nb_id
	 * 
	 * @param nbId
	 *            the value for nb_entity.nb_id
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public void setNbId(Integer nbId) {
		this.nbId = nbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_entity.nb_content
	 * 
	 * @return the value of nb_entity.nb_content
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public String getNbContent() {
		return nbContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_entity.nb_content
	 * 
	 * @param nbContent
	 *            the value for nb_entity.nb_content
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public void setNbContent(String nbContent) {
		this.nbContent = nbContent == null ? null : nbContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_entity.nb_image
	 * 
	 * @return the value of nb_entity.nb_image
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public String getNbImage() {
		return nbImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_entity.nb_image
	 * 
	 * @param nbImage
	 *            the value for nb_entity.nb_image
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public void setNbImage(String nbImage) {
		this.nbImage = nbImage == null ? null : nbImage.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_entity.nb_auther
	 * 
	 * @return the value of nb_entity.nb_auther
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public Integer getNbAuther() {
		return nbAuther;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_entity.nb_auther
	 * 
	 * @param nbAuther
	 *            the value for nb_entity.nb_auther
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public void setNbAuther(Integer nbAuther) {
		this.nbAuther = nbAuther;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_entity.nb_examiner
	 * 
	 * @return the value of nb_entity.nb_examiner
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public Integer getNbExaminer() {
		return nbExaminer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_entity.nb_examiner
	 * 
	 * @param nbExaminer
	 *            the value for nb_entity.nb_examiner
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public void setNbExaminer(Integer nbExaminer) {
		this.nbExaminer = nbExaminer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_entity.nb_pubtime
	 * 
	 * @return the value of nb_entity.nb_pubtime
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public Date getNbPubtime() {
		return nbPubtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_entity.nb_pubtime
	 * 
	 * @param nbPubtime
	 *            the value for nb_entity.nb_pubtime
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public void setNbPubtime(Date nbPubtime) {
		this.nbPubtime = nbPubtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_entity.nb_status
	 * 
	 * @return the value of nb_entity.nb_status
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public Integer getNbStatus() {
		return nbStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_entity.nb_status
	 * 
	 * @param nbStatus
	 *            the value for nb_entity.nb_status
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public void setNbStatus(Integer nbStatus) {
		this.nbStatus = nbStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_entity.nb_up
	 * 
	 * @return the value of nb_entity.nb_up
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public Integer getNbUp() {
		return nbUp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_entity.nb_up
	 * 
	 * @param nbUp
	 *            the value for nb_entity.nb_up
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public void setNbUp(Integer nbUp) {
		this.nbUp = nbUp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_entity.nb_down
	 * 
	 * @return the value of nb_entity.nb_down
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public Integer getNbDown() {
		return nbDown;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_entity.nb_down
	 * 
	 * @param nbDown
	 *            the value for nb_entity.nb_down
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public void setNbDown(Integer nbDown) {
		this.nbDown = nbDown;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_entity.nb_label
	 * 
	 * @return the value of nb_entity.nb_label
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public String getNbLabel() {
		return nbLabel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_entity.nb_label
	 * 
	 * @param nbLabel
	 *            the value for nb_entity.nb_label
	 * 
	 * @mbggenerated Mon Mar 17 10:30:24 CST 2014
	 */
	public void setNbLabel(String nbLabel) {
		this.nbLabel = nbLabel == null ? null : nbLabel.trim();
	}
}