package org.nb.mybatis.model;

public class NB_Report {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_report.Report_ID
	 * 
	 * @mbggenerated Wed Mar 19 10:28:02 CST 2014
	 */
	private Integer reportId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_report.Report_NB_ID
	 * 
	 * @mbggenerated Wed Mar 19 10:28:02 CST 2014
	 */
	private Integer reportNbId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_report.Report_Auther
	 * 
	 * @mbggenerated Wed Mar 19 10:28:02 CST 2014
	 */
	private Integer reportAuther;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_report.Report_Cause
	 * 
	 * @mbggenerated Wed Mar 19 10:28:02 CST 2014
	 */
	private Integer reportCause;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_report.Report_ID
	 * 
	 * @return the value of nb_report.Report_ID
	 * 
	 * @mbggenerated Wed Mar 19 10:28:02 CST 2014
	 */
	public Integer getReportId() {
		return reportId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_report.Report_ID
	 * 
	 * @param reportId
	 *            the value for nb_report.Report_ID
	 * 
	 * @mbggenerated Wed Mar 19 10:28:02 CST 2014
	 */
	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_report.Report_NB_ID
	 * 
	 * @return the value of nb_report.Report_NB_ID
	 * 
	 * @mbggenerated Wed Mar 19 10:28:02 CST 2014
	 */
	public Integer getReportNbId() {
		return reportNbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_report.Report_NB_ID
	 * 
	 * @param reportNbId
	 *            the value for nb_report.Report_NB_ID
	 * 
	 * @mbggenerated Wed Mar 19 10:28:02 CST 2014
	 */
	public void setReportNbId(Integer reportNbId) {
		this.reportNbId = reportNbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_report.Report_Auther
	 * 
	 * @return the value of nb_report.Report_Auther
	 * 
	 * @mbggenerated Wed Mar 19 10:28:02 CST 2014
	 */
	public Integer getReportAuther() {
		return reportAuther;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_report.Report_Auther
	 * 
	 * @param reportAuther
	 *            the value for nb_report.Report_Auther
	 * 
	 * @mbggenerated Wed Mar 19 10:28:02 CST 2014
	 */
	public void setReportAuther(Integer reportAuther) {
		this.reportAuther = reportAuther;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_report.Report_Cause
	 * 
	 * @return the value of nb_report.Report_Cause
	 * 
	 * @mbggenerated Wed Mar 19 10:28:02 CST 2014
	 */
	public Integer getReportCause() {
		return reportCause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_report.Report_Cause
	 * 
	 * @param reportCause
	 *            the value for nb_report.Report_Cause
	 * 
	 * @mbggenerated Wed Mar 19 10:28:02 CST 2014
	 */
	public void setReportCause(Integer reportCause) {
		this.reportCause = reportCause;
	}
}