package org.nb.mybatis.model;

import java.util.Date;

public class NB_Reply {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_reply.Rep_ID
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	private Integer repId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_reply.Rep_NB_ID
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	private Integer repNbId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_reply.Rep_Time
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	private Date repTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_reply.Rep_User_ID
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	private Integer repUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_reply.Rep_Rep_ID
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	private Integer repRepId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_reply.Rep_Content
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	private String repContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_reply.Rep_ID
	 * 
	 * @return the value of nb_reply.Rep_ID
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	public Integer getRepId() {
		return repId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_reply.Rep_ID
	 * 
	 * @param repId
	 *            the value for nb_reply.Rep_ID
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	public void setRepId(Integer repId) {
		this.repId = repId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_reply.Rep_NB_ID
	 * 
	 * @return the value of nb_reply.Rep_NB_ID
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	public Integer getRepNbId() {
		return repNbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_reply.Rep_NB_ID
	 * 
	 * @param repNbId
	 *            the value for nb_reply.Rep_NB_ID
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	public void setRepNbId(Integer repNbId) {
		this.repNbId = repNbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_reply.Rep_Time
	 * 
	 * @return the value of nb_reply.Rep_Time
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	public Date getRepTime() {
		return repTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_reply.Rep_Time
	 * 
	 * @param repTime
	 *            the value for nb_reply.Rep_Time
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	public void setRepTime(Date repTime) {
		this.repTime = repTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_reply.Rep_User_ID
	 * 
	 * @return the value of nb_reply.Rep_User_ID
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	public Integer getRepUserId() {
		return repUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_reply.Rep_User_ID
	 * 
	 * @param repUserId
	 *            the value for nb_reply.Rep_User_ID
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	public void setRepUserId(Integer repUserId) {
		this.repUserId = repUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_reply.Rep_Rep_ID
	 * 
	 * @return the value of nb_reply.Rep_Rep_ID
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	public Integer getRepRepId() {
		return repRepId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_reply.Rep_Rep_ID
	 * 
	 * @param repRepId
	 *            the value for nb_reply.Rep_Rep_ID
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	public void setRepRepId(Integer repRepId) {
		this.repRepId = repRepId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_reply.Rep_Content
	 * 
	 * @return the value of nb_reply.Rep_Content
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	public String getRepContent() {
		return repContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_reply.Rep_Content
	 * 
	 * @param repContent
	 *            the value for nb_reply.Rep_Content
	 * 
	 * @mbggenerated Mon Mar 17 20:32:25 CST 2014
	 */
	public void setRepContent(String repContent) {
		this.repContent = repContent == null ? null : repContent.trim();
	}
}