package org.nb.mybatis.model;

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class NB_User {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_user.ID
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_user.Name
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_user.Email
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_user.Phone
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	private String phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_user.RegisterTime
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	private Date registertime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_user.Sex
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	private Integer sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_user.Locate
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	private String locate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_user.Score
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	private Float score;

	private String password;

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column nb_user.Image
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	private String image;

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	private int status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_user.ID
	 * 
	 * @return the value of nb_user.ID
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_user.ID
	 * 
	 * @param id
	 *            the value for nb_user.ID
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_user.Name
	 * 
	 * @return the value of nb_user.Name
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_user.Name
	 * 
	 * @param name
	 *            the value for nb_user.Name
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_user.Email
	 * 
	 * @return the value of nb_user.Email
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_user.Email
	 * 
	 * @param email
	 *            the value for nb_user.Email
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_user.Phone
	 * 
	 * @return the value of nb_user.Phone
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_user.Phone
	 * 
	 * @param phone
	 *            the value for nb_user.Phone
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_user.RegisterTime
	 * 
	 * @return the value of nb_user.RegisterTime
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public Date getRegistertime() {
		return registertime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_user.RegisterTime
	 * 
	 * @param registertime
	 *            the value for nb_user.RegisterTime
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public void setRegistertime(Date registertime) {
		this.registertime = registertime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_user.Sex
	 * 
	 * @return the value of nb_user.Sex
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_user.Sex
	 * 
	 * @param sex
	 *            the value for nb_user.Sex
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_user.Locate
	 * 
	 * @return the value of nb_user.Locate
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public String getLocate() {
		return locate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_user.Locate
	 * 
	 * @param locate
	 *            the value for nb_user.Locate
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public void setLocate(String locate) {
		this.locate = locate == null ? null : locate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_user.Score
	 * 
	 * @return the value of nb_user.Score
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public Float getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_user.Score
	 * 
	 * @param score
	 *            the value for nb_user.Score
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public void setScore(Float score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column nb_user.Image
	 * 
	 * @return the value of nb_user.Image
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public String getImage() {
		return image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column nb_user.Image
	 * 
	 * @param image
	 *            the value for nb_user.Image
	 * 
	 * @mbggenerated Wed Mar 12 10:25:28 CST 2014
	 */
	public void setImage(String image) {
		this.image = image == null ? null : image.trim();
	}
}